### ISSUE TITLE
You can use the .cer file and save it with the .pem extension and use the same

### ISSUE THREAD

**Issue by blakemcbride** [adplabs/adp-connection-java#10]
You can use the .cer file and save it with the .pem extension and use the same

_Originally posted by @ADPMarketplace in https://github.com/adplabs/adp-connection-java/issues/9#issuecomment-604341720_

Which .cer file?  (ADP supplied me with several different ones as mentioned in the original post.)

Thank you.

**Comment by ADPMarketplace** [comment]
You can use : Certificate only, PEM encoded: XXX.cer from the list you have mentioned in previous post.


Thanks,
Sruthi
