### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by KSilverman** [adplabs/adp-connection-java#3]
Hi, 

I seem to have gotten this error when executing the maven command to install the project using the command "mvn clean install -e". There is also no ADPConnection.jar to add to the build path of my project.

![adp_fail](https://cloud.githubusercontent.com/assets/5942751/26634225/f1e0d950-45e3-11e7-8024-ebb4488170fc.PNG)

Any thoughts? Thanks!

Also, I'd rather import the project into eclipse, I think that'd be easier, but I can't seem to import the project either.

**Comment by ADPMarketplace** [comment]
Hi,
The end user can replace the pom.xml file (which is there in his local system) with the attached pom.xml file and run it using maven.

Please let us know if the issue still persists. Thank you.

Thanks,
Mahesh.
