### ISSUE TITLE
Unable to retrieve data out of ADP - Invalid/ missing roleCode error

### ISSUE THREAD

**Issue by sudiptodesmukh-okta** [adplabs/adp-connection-java#6]
ending 'GET' request to URL : https://uat-api.adp.com/hr/v2/workers?count=true
Key : Server ,Value : Apache-Coyote/1.1
Key : ADP-CorrelationID ,Value : 6c70459d-a281-4348-9c08-84cae67e89c3
Key : Cache-Control ,Value : no-cache, no-store, proxy-revalidate
Key : Pragma ,Value : no-cache
Key : Set-Cookie ,Value : BIGipServerp_mkplproxy-uat-dc1=57016587.20480.0000; Path=/hr/v2; Domain=uat-api.adp.com
Key : Strict-Transport-Security ,Value : max-age=31536000
Key : Content-Type ,Value : application/json
Key : Date ,Value : Fri, 13 Apr 2018 04:13:40 GMT
Key : Connection ,Value : close
Response Code : 400
response code from feature :: 400
worker response..{"confirmMessage":{"confirmMessageID":{"idValue":"12312321","schemeName":"confirmMessageID","schemeAgencyName":"APIMP"},"createDateTime":"2018-04-13T04:13:39.437Z","requestReceiptDateTime":"2018-04-13T04:13:40.707Z","protocolStatusCode":{"codeValue":400},"protocolCode":{"codeValue":"http"},"requestStatusCode":{"codeValue":"failed"},"requestMethodCode":{"codeValue":"GET"},"sessionID":{"idValue":"1lf5kyc7uqBtbb4AxuvjPBRr4So=","schemeName":"sessionID","schemeAgencyName":"APIMP"},"requestETag":"A1231234324","requestLink":{"href":"/hr/v2/workers?count=true","rel":"related","method":"GET"},"resourceMessages":[{"processMessages":[{"messageTypeCode":{"codeValue":"error"},"userMessage":{"messageTxt":"Invalid / Missing Role code"},"developerMessage":{"codeValue":"c249c755-3727-caaa-51a4-e6c0e802eb6f"}}]}]}}

Wasn't having this issue for last few months until 30 mins ago, please help!!

**Comment by ADPMarketplace** [comment]
Hi,

There was some down time with ADP Workforce Now-UAT end, because of which this issue happened. I have tried the same API and it is working as expected. 

Please check and let us know if you still face any issues.

Thanks,
Sruthi
