### ISSUE TITLE
Can't connect to IAT

### ISSUE THREAD

**Issue by arikdougherty** [adplabs/adp-connection-java#7]
When attempting to build the sample apps I am getting the following error:

Failed tests:   isConnectionIndicator(com.adp.marketplace.core.connection.core.AuthorizationCodeConnectionTest)
  connectVerifyServerErrorResponse(com.adp.marketplace.core.connection.core.AuthorizationCodeConnectionTest)
  isConnectionIndicator(com.adp.marketplace.core.connection.core.ClientCredentialsConnectionTest): expected null, but was:<HTTP/1.1 401 Unauthorized {
  disconnect(com.adp.marketplace.core.connection.core.ClientCredentialsConnectionTest): expected null, but was:<HTTP/1.1 401 Unauthorized {
  connectVerifyServerErrorResponse(com.adp.marketplace.core.connection.core.ClientCredentialsConnectionTest)

I have followed the steps outlined in the README's and am receiving this error after attempting to run pom.xml inside of eclipse to build the sample app. I attached the reports for the failed tests. 

[com.adp.marketplace.core.connection.core.AuthorizationCodeConnectionTest.txt](https://github.com/adplabs/adp-connection-java/files/2186632/com.adp.marketplace.core.connection.core.AuthorizationCodeConnectionTest.txt)
[com.adp.marketplace.core.connection.core.ClientCredentialsConnectionTest.txt](https://github.com/adplabs/adp-connection-java/files/2186633/com.adp.marketplace.core.connection.core.ClientCredentialsConnectionTest.txt)

**Comment by ADPMarketplace** [comment]
Hi, 

The certificates which are being used for this library got expired, we are working with our internal team. We will let you know once it is updated.

Thanks,
Sruthi

**Comment by jviafora** [comment]
Hi @ADPMarketplace Sruthi, any idea on how long this will take? Thanks you very much for getting this done for us, our project timeline depends on it!

**Comment by ADPMarketplace** [comment]
Hi,

By early next week it will be ready.

Thanks,
Sruthi

**Comment by jviafora** [comment]
@ADPMarketplace, any update?

**Comment by ADPMarketplace** [comment]
Hi,

We still in the process of updating the certificate.

Thanks,
Sruthi

**Comment by ADPMarketplace** [comment]
Hi Mark,

Certificates has been updated, can you please check and let us know if you see any issues.

Thanks,
Sruthi

**Comment by ADPMarketplace** [comment]
Hi,

Can you please check and confirm?

Thanks,
Sruthi

**Comment by arikdougherty** [comment]
Hello,

I was able to successfully get a token. 

Thank you
Arik

**Comment by ADPMarketplace** [comment]
Thank for the confirmation.

Thanks,
Sruthi

**Comment by lshiffer** [comment]
Are the certificates still expired?  Because I'm getting the handshake_failure despite adding to my cacerts.
