### ISSUE TITLE
Not sure which .pem file to use.

### ISSUE THREAD

**Issue by blakemcbride** [adplabs/adp-connection-java#9]
In step 2 inside ONE-TIME_CERTS_SETUP.md it tells us to execute the line: openssl pkcs12 -export -out keystore.pkcs12 -in apiclient_iat.pem -inkey apiclient_iat_key.pem

I do not know which file to use as file apiclient_iat.pem

I was given:

 as Certificate (w/ chain), PEM encoded: XXX.cer
 as Certificate only, PEM encoded: XXX.cer
 as PKCS#7, PEM encoded: XXX.crt
 as PKCS#7: XXX.p7b
 as Root/Intermediate(s) only, PEM encoded: XXX.cer
 as Intermediate(s)/Root only, PEM encoded: XXX.cer

Thank you.

Blake McBride
blake@arahant.com

**Comment by ADPMarketplace** [comment]
You can use the .cer file and save it with the .pem extension and use the same
